using System.Security.Cryptography;
using System;
using UnityEngine;
using System.Collections.Generic;


public class Homework : MonoBehaviour
{
    /*
    // √ârt√©kcsere
    int a=3; 
    int b=8;
    a+=b;
    b-=a;
    b=-b;
    a-=b;
    */
    // L√©pked√©s fix sebess√©ggel
    class StepMover:MonoBehaviour
    {
        [SerializeField] float speed;
        Vector3 target;
        void Start()
        {
            target=transform.position;
        }
        void Update()
        {
            if (Input.GetKeyDown(KeyCode.UpArrow))
            target += Vector3.up;
            if (Input.GetKeyDown(KeyCode.DownArrow))
            target += Vector3.down;
            if (Input.GetKeyDown(KeyCode.RightArrow))
            target += Vector3.right;
            if (Input.GetKeyDown(KeyCode.LeftArrow))
            target += Vector3.left;

            Vector3 selfPos = transform.position;
            transform.position = Vector3.MoveTowards(selfPos,target,speed * Time.deltaTime);
        }
    }

 

    /*
    int SzamjegyOsszeg(int n)
    {
        int sum = 0;
        while (n != 0)
        {
            int szamjegy = n % 10;
            sum += szamjegy;
            n /= 10;
        }
        return sum;
    }

    int[] sorrend(int[] array)
    {
        if (array == null)
        {
            return null;
        }
        int[] newArray = new int[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            int i2 = array.Length - 1 - i;
            newArray[i] = array[i2];
        }
        return newArray;
    }

    int[] Fibonacci(int length)
    {
        int[] result = new int[length];
        
        if (length > 0)
        {
            result[0] = 0;
        }
        if (length > 1)
        {
            result[1] = 1;
        }
        for (int i = 2; i < length; i++)
        {
            result[i] = result[i - 1] + result[i - 2];
        }
        return result;
    }

    int Betuszamlalo(string s)
    {
        List<char> characters = new List<char>();
        foreach (char c in s)
        {
            if (!characters.Contains(c))
            {
                characters.Add(c);
            }
        }
        return characters.Count;

    }
    /*
    class NormalizedDirectionVector : MonoBehaviour
    {
        [SerializeField] Vector2 a, b;

        [SerializeField] int stepCount;
        [SerializeField] Vector2 step;

        void OnValidate()
        {
            Vector2 dirVec = b - a;
            float tavolsag = dirVec.magnitude;
            stepCount = Mathf.CeilToInt(tavolsag);
            step = dirVec / stepCount;
        }
    }
    */
    

    /*
    // [SerializeField] int a;
    // [SerializeField] int b;
    // Start is called before the first frame update
    void Start()
    {
        // 1. feladat
        int a = 38;
        int b = 5;
        float c = (a / b);
        int dd = a % b;
        Debug.Log("{a}-ban a(z) {b} megvan {c} -szer, marad√©k: {d}.");

        // 2. feladat
        a = 2; b = 4; c = 5;
        string d = "D", e = "E", f = "F";

        int x1 = a + b + c;
        string x2 = a + b + e;
        string x3 = b + d + c;
        string x4 = f + a + b;

        float x5 = a + b * c;
        x5 /= 8;
        float x6 = x5 / b;
        x6++;
        float x7 = x6 / 2f;
        x7--;
        float x8 = -1 * x7;
        x8 *= x8;

        // 3. feladat
        int number;
        int summa;
        summa = 0;
        for (int i = 1; i <= number; i++)
        {
            summa += i;
        }
        Debug.Log("Az osszeg: {summa}.");

        // 4. feladat
        int number = 1;
        bool fizz = i % 3 == 0;
        bool fizz = i % 5 == 0;
        for (int i = 1; i <= number; i++)
        {
            if (fizz && buzz)
            {
                Debug.Log("FizzBuzz");
            }
            else if (fizz)
            {
                Debug.Log("fizz");
            }
            else if (buzz)
            {
                Debug.Log("buzz");
            }
            else
            {
                Debug.Log(i);
            }
        }


        // 5. feladat
        int baseNumber = 1;
        int exponent = 1;

        int result;

        result = Math.Pow(baseNumber, exponent);

        /*
        for (int i = 0; i < exponent; i++)
        {
            result*=baseNumber;
        }
        */
    /*
        Debug.Log($"Az eredm√©ny: {result}");

        // 6. feladat
        for (int i = 1; i <= 10; i++)
        {
            for (int j = 1; j < 10; j++)
            {
                Debug.Log($"{i}*{j}={i * j}");
            }
        


    // Update is called once per frame
    void Update()
    {

    }
*/

}

   /*
    √çrj komponenst, ami egy 6 √°g√∫ keresztet rajzol a t√©rben pont oda, ahol a komponenshez tartoz√≥ GameObject elhelyezkedik!

A keresztnek 3 egym√°ssal mer≈ëleges tengelye legyen!

A kereszt √°gai arra mutassanak, amerre a GameObject lok√°lis jobbra, balra, fel, le, el≈ëre √©s h√°tra ir√°nya mutat.

A kereszt √°gai meghat√°rozott sz√≠n≈±ek legyenek:

- X tengely: üî¥ Piros
- Y tengely: üü¢ Z√∂ld
- Z tengely: üîµ K√©k

Az √°gak hossza megegyezik. A hossz egy `[SerializeField]` mez≈ëvel be√°ll√≠that√≥.

B√≥nusz: A pozit√≠v ir√°nyokba (jobbra, fel, el≈ëre) mutat√≥ √°gak v√©g√©re rajzoljatok egy kis g√∂mb√∂t!
    */


public class Tester : MonoBehaviour
{
	[SerializeField] float length;  // Egy tengely hossza
    
    void OnDrawGizmos()
    { 
	    Vector3 p = transform.position;

        DrawAxis(p, Vector3.right, Color.red);
        DrawAxis(p, Vector3.up, Color.green);
        DrawAxis(p, Vector3.forward, Color.blue);
    }
    
    void DrawAxis(Vector3 center, Vector3 axis, Color color)
    {
		Vector3 direction = length * transform.TransformDirection(axis);
		Gizmos.color = color;
		Gizmos.DrawLine(center - direction, center + direction);
		Gizmos.DrawSphere(center + direction, 0.1f * length);
    }
}

/*
√çrj k√∂vet≈ërak√©ta komponenst! A komponens-nek van egy `[SerializeField] Transform target` be√°ll√≠t√°sa. 
A k√∂vet≈ërak√©ta mindig ezt a c√©lpontot pr√≥b√°lja el√©rni a 3D t√©rben.

A rak√©ta mindig csak‚Ä¶

- el≈ërefel√© haladhat egy be√°ll√≠that√≥ fix sebess√©ggel, √©s
- legfeljebb fix sz√∂gsebess√©ggel fordulhat.
*/
public class Rocket : MonoBehaviour
{
	[SerializeField] Transform target;
	[SerializeField] float speed = 5;
	[SerializeField] float angularSpeed = 180;
	
	void Update()
	{
		Transform self = transform;
		
		Vector3 targetDirection = target.position - self.position;  // Ebben az ir√°nyban van a c√©l
		Quaternion targetRotation = Quaternion.LookRotation(targetDirection);   // Ahhoz ebbe az ir√°nyba akarunk fordulni
		
		// Fordul√°s:
		float maxAngle = angularSpeed * Time.deltaTime;  // Maximum ekkora sz√∂gben fordulhatunk most
		self.rotation = Quaternion.RotateTowards(self.rotation, targetRotation, maxAngle);  // Towards met√≥dus
		
		// Halad√°s:
		float offset = speed * Time.deltaTime;   // Ennyit l√©p√ºnk el≈ëre
		self.position += self.forward * offset;  // El≈ëre ir√°nyba megy√ºnk
	}
}

/*
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.0</TargetFramework>
    </PropertyGroup>
</Project>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.0</TargetFramework>
    </PropertyGroup>
</Project>
elso
using UnityEngine;

public class ConnectingLine : MonoBehaviour
{
    [SerializeField] Transform other;
    [SerializeField] float maxLength = 10;

    void OnDrawGizmos()
    {
        if (other == null)
            return;

        Vector3 otherPos = other.position;
        Vector3 selfPos = transform.position;
        
        // T√°vols√°g kisz√°m√≠t√°sa
        float distance = Vector3.Distance(otherPos, selfPos);
        
        // Ha hat√°r√©rt√©ken bel√ºl van a m√°sik objektum
        if (distance <= maxLength)
        {
            if (distance > maxLength * 0.9f)   // Ha 90% felett
                Gizmos.color = Color.red;
            else
                Gizmos.color = Color.green;
            
            Gizmos.DrawLine(otherPos, selfPos);
        }
    }
}
masodik
public classChildRotator: MonoBehaviour
{
    [SerializeField] floatbaseAngularSpeed= 1f;

    void Update()
    {
        foreach (Transform child in GetComponentsInChildren<Transform>())
        {
            if (child.GetComponent<MeshRenderer>() != null)
            {
                float angularSpeed = baseAngularSpeed;
								
								//B√≥nusz feladat:
								angularSpeed /= Vector3.Distance(child.position, transform.position);

                child.Rotate(0, angularSpeed * Time.deltaTime, 0);
            }
        }
    }
}
harmadik
string[] Combine(string[] a1, string[] a2)
{
	string[] c = new string[a1.Length + a2.Length];
	
	for (int i = 0; i < a1.Length; i++)
		c[i] = a1[i];
	
	for (int i = 0; i < a2.Length; i++)
		c[a1.Length + i] = a2[i];
	
	return c;
}
bonusz
int BinaryToDecimal(int binaryNum)
{
    int decimalNum = 0;    // Kinull√°zom a v√©geredm√©nyt 
    int digitValue = 1;    // Ebben sz√°molom, hogy az egyes helyi√©rt√©ken mennyivel szorzunk

    while (binaryNum > 0)  // Egyenk√©nt v√©gigmegyek a bin√°ris sz√°m minden sz√°mjegy√©n
    {
        int digit = binaryNum % 10;    // Lev√°gjuk az utols√≥ sz√°mjegyet

        if (digit > 1)         // Ha b√°rmelyik sz√°mjegy nem 0 vagy 1
        {
            decimalNum = 0;    // akkor az eredm√©ny 0
            break;             // √°s kil√©p√ºnk a ciklusb√≥l
        }

        decimalNum += digit * digitValue;

        binaryNum = binaryNum / 10;   // T√∂rl√∂m az utols√≥ sz√°mjegyet (Azt m√°r kezeltem)
        digitValue *= 2;              // K√∂vetkez≈ë helyi√©rt√©k m√°r dupla akkora szorz√≥j√∫
    }

    return decimalNum;
}
/*
- **L√©zer c√©lz√≥**
    
    √çrj komponenst, ami egy sugarat l≈ë (Raycasting) saj√°t poz√≠ci√≥j√°b√≥l lok√°lis el≈ëre ir√°ny√°ba!
    
    A komponensnek [SerializeField] be√°ll√≠t√°sk√©nt megadhat√≥ GameObject-ek egy t√∂mbje.
    
    Ha a sug√°rvet√©s c√©lt tal√°lt, akkor t√∂mb elemeit felsorakoztatja a c√©lz√°s √©s tal√°lat pontjai k√∂z√© egyenl≈ë t√°vols√°gra. Ha a sug√°rvet√©s nem tal√°lt c√©lt, a t√∂mb elemeit inaktiv√°lja!
    
    Lehessen a komponensnek be√°ll√≠tani maxim√°lis t√°vols√°got!

    using UnityEngine;

public class Pointer : MonoBehaviour
{ 
    [SerializeField] float rayLength = 100f;
    [SerializeField] GameObject[] objects;

    void Update()
    {
        Vector3 position = transform.position; // Poz√≠ci√≥
        Ray ray = new Ray(position, transform.forward); // El≈ëre mutat√≥ sug√°r

        bool isHit = Physics.Raycast(ray, out RaycastHit hit, rayLength); // Sug√°rvet√©s = raycast

        foreach (GameObject o in objects)   // V√©gigmegyek az √∂sszes objektumon
            o.SetActive(isHit);             // Ki vgy be kapcsolom az objektumokat
                                            // f√ºgg≈ëen att√≥l, hogy t√∂rt√©nt e tal√°lat

        if (isHit) // Ha van tal√°lat
        {
            for (int index = 0; index < objects.Length; index++) // Az √∂sszese elemre:
            {
                float rate = index / (objects.Length - 1f); // 0-1 k√∂z√∂tti √©rt√©k
                Vector3 p = Vector3.Lerp(position, hit.point, rate); // Line√°ris interpol√°ci√≥
                objects[index].transform.position = p; // Poz√≠ci√≥ be√°ll√≠t√°sa
            }
        }
    }

    void OnDrawGizmos()
    {
        Vector3 position = transform.position;                                  // Poz√≠ci√≥
        Ray ray = new Ray(position, transform.forward );            // El≈ëre mutat√≥ sug√°r 
        Gizmos.color = Color.red;                                               // Gizmos sz√≠ne
        Gizmos.DrawLine(ray.origin, ray.origin + (ray.direction * rayLength));  // Sug√°r kirajzol√°sa 
    }

    2.
    √çrj bolyg√≥ (Planet) komponenst, aminek gravit√°ci√≥s hat√°sa van minden t√∂bbi bolyg√≥ra.

Minden bolyg√≥nak van egy be√°ll√≠that√≥ t√∂mege.

Minden test vonz egy m√°sik testet a Newtoni t√∂megvonz√°s t√∂rv√©nye szerint.

A megold√°shoz ne haszn√°lj RigidBody-t!
using UnityEngine;

public class Planet : MonoBehaviour
{
    [SerializeField, Min(0)] float mass = 1;   // t√∂meg 
    
    Vector3 velocity;             // Sebess√©gvektor

    // Kisz√°molom a m√©retet a t√∂meg alapj√°n (NEM VOLT FELADAT)
    void OnValidate()
    {
        float scale = Mathf.Pow(mass, 1/3f); // a t√∂meg k√∂bgy√∂ke
        transform.localScale = new Vector3(scale, scale, scale);
    }

    // A gyorsul√°st √©s lassul√°st √©rdemes a FixedUpdate-ben kezelni:
    void FixedUpdate()
    {
        float gravity = 5; // Newton f√©le gravitat√°ci√≥s √°lland√≥ (saj√°t √©rt√©kkel)
        foreach (var otherPlanet in FindObjectsOfType<Planet>())  // Minden egy√©b bolyg√≥ hat r√°nk
        {
            if(otherPlanet == this)    // Saj√°t mag√°ra nem hat a bolyg√≥
                continue; // K√∂vetkez≈ë bolyg√≥ra l√©p√ºnk
            
            Vector3 distanceVector = otherPlanet.transform.position - transform.position;
            if(distanceVector == Vector3.zero)
                continue; // K√∂vetkez≈ë bolyg√≥ra l√©p√ºnk
            
            float distance = distanceVector.magnitude;      // T√°vols√°g
            Vector3 direction = distanceVector.normalized;  // Ir√°nyvektor
            
            float acceleration = gravity * otherPlanet.mass / distance;
            // NEM A T√ÅVOLS√ÅG N√âGYZET√âVEL OSZTOK!!!
            // Mint az a val√≥s fizika szerint t√∂rt√©nne!
            // Ennek oka, hogy t√∫l neh√©z vele stabil rendszert √©p√≠teni, ami nem esik sz√©t.
            
            velocity += direction * (acceleration * Time.fixedDeltaTime); // gravit√°ci√≥s gyorsul√°s
        }
    }
    
    // Az elmozdul√°st √©rdemes az Update-ben kezelni:
    void Update()
    {
        transform.position += velocity * Time.deltaTime;
    }

    // Sebess√©gvektor kirajzol√°sa (NEM VOLT FELADAT)
    void OnDrawGizmos()
    {
        Gizmos.color = new Color(1,1,1,0.25f); // √Åtl√°tsz√≥ feh√©r 
        Gizmos.DrawLine(transform.position, transform.position + (velocity * 0.5f)); // Sebess√©gvektor
    }
}
3.
// List√°val √©s triggerekkel

using System.Collections.Generic;
using UnityEngine;

class GravityModifier : MonoBehaviour
{
		//Kifejtett gyorsul√°s
    [SerializeField] Vector3 gravity = new(0, 10, 0); 

		// Itt t√°rolom az √©ppen triggeren bel√ºl l√©v≈ëket
    List<Rigidbody> _rigidbodies = new();

		// T√°rolom a bel√©p≈ëket
    void OnTriggerEnter(Collider other)
    {
        Rigidbody rb = other.attachedRigidbody;
        if (rb != null)            
            _rigidbodies.Add(rb);
    }
    
		// T√∂rl√∂m a list√°b√≥l a t√°voz√≥kat
    void OnTriggerExit(Collider other)
    {
        Rigidbody rb = other.attachedRigidbody;
        if (rb != null)
            _rigidbodies.Remove(rb);
    }

    void FixedUpdate()
    { 
				// Hozz√°adom a gyorsul√°st
        foreach (Rigidbody rb in _rigidbodies)
		        rb.AddForce(gravity, ForceMode.Acceleration);
    }
}
}
*/
/*
using System.Collections.Generic;
using UnityEngine;

public class Pointer : MonoBehaviour
{ 
    [SerializeField] float rayLength = 100f;           // Sug√°rvet√©s maxim√°lis hossza
    [SerializeField] float distance = 0.25f;           // K√©t c√©lz√≥pont t√°vols√°ga
    [SerializeField] GameObject prototype;             // Ebb≈ël k√©sz√≠t√ºnk m√°solatokat

    List<GameObject> objects = new List<GameObject>(); // Ebbe a list√°ba tessz√ºk ez elemeket

    void Update()
    {
        Vector3 position = transform.position;            // Poz√≠ci√≥
        Vector3 forward = transform.forward;              // El≈ëre ir√°ny
        Ray ray = new Ray(position, forward); // El≈ëre mutat√≥ sug√°r

        bool isHit = Physics.Raycast(ray, out RaycastHit hit, rayLength); // Sug√°rvet√©s = raycast 
        
        int count = 0; // H√°ny elemet rejzoljuk ki
        
        if (isHit) // Ha van tal√°lat
        {
            // H√°ny elemet rejzoljuk ki:
            count = Mathf.CeilToInt(Vector3.Distance(position, hit.point) / distance);
            
            // Ha nincsenek l√©trehozva, p√©ld√°nyos√≠tom √©s elt√°rolom a c√©lz√≥pontokat
            while (count > objects.Count)
            {
                GameObject newInstance = Instantiate(prototype);
                objects.Add(newInstance);
            }
            
            for (int i = 0; i < count; i++)     // Az √∂sszese megjelen√≠tend≈ë objektumra:
            {
                objects[i].SetActive(true);                         // bekapcsol√°s
                Vector3 p = position + (i * distance * forward);    // poz√≠ci√≥ kisz√°m√≠t√°sa
                objects[i].transform.position = p;                  // Poz√≠ci√≥ be√°ll√≠t√°sa
            }
        }

        // Az √∂sszese NEM megjelen√≠tend≈ë objektumra:
        for (int i = count; i < objects.Count; i++)
            objects[i].SetActive(false);  // kikapcsol√°s
    }

    void OnDrawGizmos()
    {
        Vector3 position = transform.position;                                  // Poz√≠ci√≥
        Ray ray = new Ray(position, transform.forward );            // El≈ëre mutat√≥ sug√°r 
        Gizmos.color = Color.red;                                               // Gizmos sz√≠ne
        Gizmos.DrawLine(ray.origin, ray.origin + (ray.direction * rayLength));  // Sug√°r kirajzol√°sa 
    }
}
2. feladat
using UnityEngine;
 
public class Magnet : MonoBehaviour
{
    [SerializeField] new Rigidbody2D rigidbody;
    [SerializeField] float power;
    [SerializeField] bool isPositive;
 
    void FixedUpdate()
    {
        Magnet[] magnets = FindObjectsOfType<Magnet>();

//  	  for(int i = 0; i < magnets.Length; i++) // for ciklus is lehetne
//			{
//					Magnet other = magnets[i];

        foreach (Magnet other in magnets)       // for ciklus is lehetne
        {                                       // L√°tsd fentebb ‚Üë

            if (other == this) continue;        // Saj√°t mag√°ra nem hat
            
            Vector2 vector = other.transform.position - transform.position;
            float distance = vector.magnitude;  // T√°vols√°g
            Vector2 direction = vector;         // Ir√°ny
            
            if(isPositive != other.isPositive)  // Ha ellent√©tesek a p√≥lusok
                direction *= -1;                // akkor vonzz√°k egym√°st
            
            //A kifejtett er≈ë:

						// egyenesen ar√°nyos mindk√©t p√≥lus erej√©vel,
            float force = power * other.power;
						// √©s ford√≠tottan a t√°vols√°g n√©gyzet√©vel.
            force /= distance * distance;
            
						// Er≈ët fejt√ºnk ki a m√°sikra
            other.rigidbody.AddForce(direction * force);
        }
    }
}
3. feladat

K√©sz√≠ts bomb√°t, ami egy id≈ë letelte ut√°n ell√∂ki a k√∂r√ºl√∂tte l√©v≈ë RigidBody-kat √©s megsemmis√≠ti √∂nmag√°t.

A robban√°snak van egy be√°ll√≠that√≥ ereje √©s hat√≥t√°vols√°ga.

A hat√≥t√°v sz√©l√©hez k√∂zeledve gyeng√ºl a l√∂k√©s ereje.

- Illusztr√°ci√≥
    
    [2022-10-24_18-13-03-523 (2).mp4](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/62778800-125d-47b5-ad56-eb62f4e897fd/2022-10-24_18-13-03-523_(2).mp4)
    
- Megold√°s
using UnityEngine;

public class Bomb : MonoBehaviour
{
    [SerializeField] float delay = 5f;
    [SerializeField] float force = 25f;
    [SerializeField] float range = 5f;
    [SerializeField] float up = 0.5f;
    
    float _startTime;

    void Start()
    {
        _startTime = Time.time;
    }

    void Update()
    {
        if (Time.time - _startTime > delay)
        {
            Explode();
            Destroy(gameObject);
        }
    }

    void Explode()
    {
        Rigidbody[] rigidbodies = FindObjectsOfType<Rigidbody>();
        foreach (Rigidbody rb in rigidbodies)
						rb.AddExplosionForce(
								force,
								transform.position,
								range,
								up,
								ForceMode.Impulse); 
	  }
}
*/